# Path to your dotfiles relative to your $HOME directory
dotfiles_dir = ".dotfiles"

[settings.dots]
alacritty = { source = "config/alacritty", target = ".config/alacritty" }
nwg-launchers = { source = "config/nwg-launchers", target = ".config/nwg-launchers" }
sway = { source = "config/sway", target = ".config/sway" }
swaylock = { source = "config/swaylock", target = ".config/swaylock" }
waybar = { source = "config/waybar", target = ".config/waybar" }
wofi = { source = "config/wofi", target = ".config/wofi" }

zfunctions = { source = "zfunctions", target = ".zfunctions" }
tmux = { source = "tmux.conf", target = ".tmux.conf" }
vim = { source = "vim", target = ".vim" }
vimrc = { source = "vimrc", target = ".vimrc" }
zshrc = { source = "zshrc", target = ".zshrc" }

